# Test your FastAPI endpoints
### Insert a user

POST http://127.0.0.1:8000/user/insert
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "company_id": 1,
  "department_id": 3,
  "email": "Bruger3@test.com",
  "password": "123",
  "firstname": "Ham",
  "lastname": "Der",
  "phone_number": "1234567890",
  "user_role": "user"
}

> {% client.assert(response.status === 200, "Insert user has failed the test"); %}

### Get token by logging in
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123"
}

> {%
    if (response.status !== 200){
        client.global.set("token", "");
    } else {
        client.global.set("token", response.body.token);
    }
    const token = client.global.get("token");
    console.log(token);
    client.assert(response.status === 200, "Get token by logging in has failed the test");
%}

### Get a user by ID

GET http://127.0.0.1:8000/user/getbyid?users_id=1
Accept: application/json
Authorization: Bearer {{token}}

> {% client.assert(response.status === 200, "Get user by Id has failed the test"); %}

### Get template questions

GET http://127.0.0.1:8000/apv/get_template_questions?apv_type=Murervirksomheder
Accept: application/json
Authorization: Bearer {{token}}

> {% client.assert(response.status === 200, "Get template questions has failed the test"); %}

### Get types by category name

GET http://127.0.0.1:8000/apv/get_types?apv_category=Bygge og anlæg
Accept: application/json
Authorization: Bearer {{token}}

> {% client.assert(response.status === 200, "Get types by category name has failed the test"); %}

### Get departments and users by company_id

GET http://127.0.0.1:8000/department/get_departments_and_users?company_id=1
Accept: application/json
Authorization: Bearer {{token}}

> {% client.assert(response.status === 200, "Get departments and users by company_id has failed the test"); %}

### Get remaining apvs by user_id

GET http://127.0.0.1:8000/apv/get_remaining_apvs?users_id=1
Accept: application/json
Authorization: Bearer {{token}}

> {% client.assert(response.status === 200, "Get remaining apvs by user_id has failed the test"); %}

### Get questions by apv_id

GET http://127.0.0.1:8000/apv/get_questions?apv_id=24
Accept: application/json
Authorization: Bearer {{token}}

> {% client.assert(response.status === 200, "Get questions by apv_id has failed the test"); %}

### Get previous apvs by company_id

GET http://127.0.0.1:8000/apv/get_previous_apvs?company_id=1
Accept: application/json
Authorization: Bearer {{token}}

> {% client.assert(response.status === 200, "Get previous apvs by company_id has failed the test"); %}

###