# Test your FastAPI endpoints

### Get token by logging in

POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "password123"
}

### Test Token Usage

GET http://127.0.0.1:8000/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTI2NjU5NTAsImlhdCI6MTcxMjY2NTY1MCwic3ViIjoxfQ.BVniLyj462k2wgGyB73fSohjZrcHqevS1L3Qe8dc-Js

### Insert a user

POST http://127.0.0.1:8000/user/insert
Content-Type: application/json

{
  "company_id": null,
  "department_id": null,
  "email": "test@test.com",
  "password": "123",
  "firstname": "Emil",
  "lastname": "Skov",
  "phone_number": "1234567890",
  "user_role": "admin"
}

### Get a user by ID

GET http://127.0.0.1:8000/user/getbyid?user_id=1
Accept: application/json

### Get template questions

GET http://127.0.0.1:8000/apv/get_template_questions?apv_type=Murervirksomheder
Accept: application/json

###


