# Test your FastAPI endpoints

### Get token by logging in

POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "password123"
}

### Test Token Usage

GET http://127.0.0.1:8000/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTI2NjU5NTAsImlhdCI6MTcxMjY2NTY1MCwic3ViIjoxfQ.BVniLyj462k2wgGyB73fSohjZrcHqevS1L3Qe8dc-Js

### Insert a user

POST http://127.0.0.1:8000/user/insert
Content-Type: application/json

{
  "company_id": 1,
  "department_id": 3,
  "email": "Bruger2sd@test.com",
  "password": "1232",
  "firstname": "Knud",
  "lastname": "Larsen",
  "phone_number": "1234567890",
  "user_role": "user"
}

### Get a user by ID

GET http://127.0.0.1:8000/user/getbyid?user_id=1
Accept: application/json

### Get template questions

GET http://127.0.0.1:8000/apv/get_template_questions?apv_type=Murervirksomheder
Accept: application/json

### Get types by category name

GET http://127.0.0.1:8000/apv/get_types?apv_category=Bygge og anlæg
Accept: application/json

### Get departments and users by company_id

GET http://127.0.0.1:8000/department/get_departments_and_users?company_id=1
Accept: application/json

### Get remaining apvs by user_id

GET http://127.0.0.1:8000/apv/get_remaining_apvs?user_id=1
Accept: application/json

### Get questions by apv_id

GET http://127.0.0.1:8000/apv/get_questions?apv_id=24
Accept: application/json

###